### ISSUE TITLE
Mistaken use of `Framework :: Hypothesis` trove classifier?

### ISSUE THREAD

**Issue by Zac-HD** [treenoder/reds#1]
Your PyPI metadata includes

https://github.com/treenoder/reds/blob/cc473aa01be3eee94f48c28b254b9217c04afa04/setup.py#L33

but you don't seem to be using [Hypothesis](https://pypi.org/project/hypothesis/).  Maybe a copy-paste error?

**Comment by treenoder** [comment]
yes, exactly)
thanks!
